[package]
name = "rust-login"
version = "0.1.0"
edition = "2024"

[dependencies]
quick-xml = { version = "0.36", features = ["serialize"] }
serde = { version = "1.0", features = ["derive"] }
libc = "0.2"

